export const ADMIN_RESTRO_REQUEST = 'ADMIN_RESTRO_REQUEST';
export const ADMIN_RESTRO_SUCCESS = 'ADMIN_RESTRO_SUCCESS'
export const ADMIN_RESTRO_ERROR = 'ADMIN_RESTRO_ERROR';

export const ADMIN_RESTRO_ADD_REQUEST = 'ADMIN_RESTRO_ADD_REQUEST';
export const ADMIN_RESTRO_ADD_SUCCESS = 'ADMIN_RESTRO_ADD_SUCCESS'
export const ADMIN_RESTRO_ADD_ERROR =   'ADMIN_RESTRO_ADD_ERROR';

export const ADMIN_RESTRO_DEL_REQUEST = 'ADMIN_RESTRO_DEL_REQUEST';
export const ADMIN_RESTRO_DEL_SUCCESS = 'ADMIN_RESTRO_DEL_SUCCESS'
export const ADMIN_RESTRO_DEL_ERROR =   'ADMIN_RESTRO_DEL_ERROR';

export const ADMIN_RESTRO_UPDATE_REQUEST = 'ADMIN_RESTRO_UPDATE_REQUEST';
export const ADMIN_RESTRO_UPDATE_SUCCESS = 'ADMIN_RESTRO_UPDATE_SUCCESS'
export const ADMIN_RESTRO_UPDATE_ERROR =   'ADMIN_RESTRO_UPDATE_ERROR';

export const ADMIN_SPA_REQUEST = 'ADMIN_SPA_REQUEST';
export const ADMIN_SPA_SUCCESS = 'ADMIN_SPA_SUCCESS'
export const ADMIN_SPA_ERROR = 'ADMIN_SPA_ERROR';

export const ADMIN_SPA_ADD_REQUEST = 'ADMIN_SPA_ADD_REQUEST';
export const ADMIN_SPA_ADD_SUCCESS = 'ADMIN_SPA_ADD_SUCCESS'
export const ADMIN_SPA_ADD_ERROR =   'ADMIN_SPA_ADD_ERROR';

export const ADMIN_SPA_DEL_REQUEST = 'ADMIN_SPA_DEL_REQUEST';
export const ADMIN_SPA_DEL_SUCCESS = 'ADMIN_SPA_DEL_SUCCESS'
export const ADMIN_SPA_DEL_ERROR =   'ADMIN_SPA_DEL_ERROR';

export const ADMIN_SPA_UPDATE_REQUEST = 'ADMIN_SPA_UPDATE_REQUEST';
export const ADMIN_SPA_UPDATE_SUCCESS = 'ADMIN_SPA_UPDATE_SUCCESS'
export const ADMIN_SPA_UPDATE_ERROR =   'ADMIN_SPA_UPDATE_ERROR';

export const ADMIN_HEALTH_ADD_SUCCESS = 'ADMIN_HEALTH_ADD_SUCCESS'
export const ADMIN_HEALTH_ADD_REQUEST = 'ADMIN_HEALTH_ADD_REQUEST';
export const ADMIN_HEALTH_ADD_ERROR =   'ADMIN_HEALTH_ADD_ERROR';

export const ADMIN_HEALTH_DEL_SUCCESS = 'ADMIN_HEALTH_DEL_SUCCESS'
export const ADMIN_HEALTH_DEL_REQUEST = 'ADMIN_HEALTH_DEL_REQUEST';
export const ADMIN_HEALTH_DEL_ERROR =   'ADMIN_HEALTH_DEL_ERROR';

export const ADMIN_HEALTH_UPDATE_REQUEST = 'ADMIN_HEALTH_UPDATE_REQUEST';
export const ADMIN_HEALTH_UPDATE_SUCCESS = 'ADMIN_HEALTH_UPDATE_SUCCESS'
export const ADMIN_HEALTH_UPDATE_ERROR =   'ADMIN_HEALTH_UPDATE_ERROR';

export const ADMIN_HEALTH_REQUEST = 'ADMIN_HEALTH_REQUEST';
export const ADMIN_HEALTH_SUCCESS = 'ADMIN_HEALTH_SUCCESS'
export const ADMIN_HEALTH_ERROR =   'ADMIN_HEALTH_ERROR';


export const ADMIN_USER_REQUEST = 'ADMIN_USER_REQUEST';
export const ADMIN_USER_SUCCESS = 'ADMIN_USER_SUCCESS'
export const ADMIN_USER_ERROR =   'ADMIN_USER_ERROR';

export const ADMIN_USER_CHANGE_REQUEST = 'ADMIN_USER_CHANGE_REQUEST';
export const ADMIN_USER_CHANGE_SUCCESS = 'ADMIN_USER_CHANGE_SUCCESS'
export const ADMIN_USER_CHANGE_ERROR =   'ADMIN_USER_CHANGE_ERROR';

