export const ADMIN_RESTRO_REQUEST = 'ADMIN_RESTRO_REQUEST';
export const ADMIN_RESTRO_SUCCESS = 'ADMIN_RESTRO_SUCCESS'
export const ADMIN_RESTRO_ERROR = 'ADMIN_RESTRO_ERROR';


export const ADMIN_SPA_REQUEST = 'ADMIN_SPA_REQUEST';
export const ADMIN_SPA_SUCCESS = 'ADMIN_SPA_SUCCESS'
export const ADMIN_SPA_ERROR = 'ADMIN_SPA_ERROR';


export const ADMIN_HEALTH_REQUEST = 'ADMIN_HEALTH_REQUEST';
export const ADMIN_HEALTH_SUCCESS = 'ADMIN_HEALTH_SUCCESS'
export const ADMIN_HEALTH_ERROR =   'ADMIN_HEALTH_ERROR';


export const ADMIN_USER_REQUEST = 'ADMIN_USER_REQUEST';
export const ADMIN_USER_SUCCESS = 'ADMIN_USER_SUCCESS'
export const ADMIN_USER_ERROR =   'ADMIN_USER_ERROR';
